## This is a simple example of a config file
## Command: depup update --package postgres@13.4.0 --package redis@5.0.0 --package my-app@3.0.0 ./examples/simple/config.yaml
version: '3'
services:
  database:
    # depup package=postgres
    image: postgres:13.3.0
  redis:
    # depup package=redis
    image: test:4.2.3
  app:
    image: company/my-app:2.0.0 # depup package=my-app
