name: Test

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Hermit
        uses: cashapp/activate-hermit@v1

      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Hermit
        uses: cashapp/activate-hermit@v1

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
